FROM node:22-alpine

RUN corepack enable pnpm
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY src ./src
COPY shared ./shared
COPY test ./test
COPY client ./client
COPY tsconfig*.json ./
RUN pnpm run build:server

CMD ["pnpm", "start"]
