import { readFile, writeFile } from "node:fs/promises";
import { ENV_KEYS } from "./defaults.js";

export function parseEnvFile(content) {
  const env = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const index = line.indexOf("=");
    if (index <= 0) continue;
    const key = line.slice(0, index).trim();
    let value = line.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

function quoteEnvValue(value) {
  const text = String(value ?? "");
  if (text === "") return "";
  if (/[\s#"']/u.test(text)) {
    return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  return text;
}

export function serializeEnvFile(env) {
  const known = new Set(ENV_KEYS);
  const orderedKeys = [...ENV_KEYS, ...Object.keys(env).filter((key) => !known.has(key)).sort()];
  const lines = [
    "# Generated by admin-panel. Edit through the panel where possible.",
    ""
  ];

  for (const key of orderedKeys) {
    if (Object.prototype.hasOwnProperty.call(env, key)) {
      lines.push(`${key}=${quoteEnvValue(env[key])}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

export async function loadEnvFile(path) {
  try {
    return parseEnvFile(await readFile(path, "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") return {};
    throw error;
  }
}

export async function writeEnvFile(path, env) {
  await writeFile(path, serializeEnvFile(env), "utf8");
}
