// Generated by tools/calibrate-radars.py --write. Image registration evidence is kept for tests.
// Source: https://github.com/MurkyYT/cs2-map-icons (CS2 radar images and overview data).
export const BUNDLED_RADAR_CALIBRATIONS = [
  {
    "mapName": "de_mirage",
    "radarUrl": "/maps/mirage.webp",
    "radarWidth": 1374,
    "radarHeight": 1196,
    "projection": {
      "xScale": 0.00023288761616038019,
      "xOffset": 0.641505295225242,
      "yScale": -0.00026728343436025815,
      "yOffset": 0.27477522679886707
    }
  },
  {
    "mapName": "de_dust2",
    "radarUrl": "/maps/dust2.webp",
    "radarWidth": 1516,
    "radarHeight": 1619,
    "projection": {
      "xScale": 0.00023977726742690543,
      "xOffset": 0.5494400139369874,
      "yScale": -0.00022472851849519363,
      "yOffset": 0.719982732182584
    }
  },
  {
    "mapName": "de_inferno",
    "radarUrl": "/maps/inferno.webp",
    "radarWidth": 1500,
    "radarHeight": 1491,
    "projection": {
      "xScale": 0.0002174722487267052,
      "xOffset": 0.4016340927947475,
      "yScale": -0.00021901508547209934,
      "yOffset": 0.8134173121251856
    }
  },
  {
    "mapName": "de_ancient",
    "radarUrl": "/maps/ancient.webp",
    "radarWidth": 1290,
    "radarHeight": 1467,
    "projection": {
      "xScale": 0.00024752518679158335,
      "xOffset": 0.6138074972322402,
      "yScale": -0.00021803167321798693,
      "yOffset": 0.4208756829767866
    }
  },
  {
    "mapName": "de_cache",
    "radarUrl": "/maps/cache.webp",
    "radarWidth": 2048,
    "radarHeight": 1596,
    "projection": {
      "xScale": 0.00017753563443544592,
      "xOffset": 0.35494877577726114,
      "yScale": -0.00022780076009209339,
      "yOffset": 0.5968513644347279
    }
  },
  {
    "mapName": "de_overpass",
    "radarUrl": "/maps/overpass.webp",
    "radarWidth": 1274,
    "radarHeight": 1632,
    "projection": {
      "xScale": 0.00024194593226139544,
      "xOffset": 0.9788862400025881,
      "yScale": -0.00018858900244871158,
      "yOffset": 0.3326617614659683
    }
  },
  {
    "mapName": "de_train",
    "radarUrl": "/maps/train.webp",
    "radarWidth": 1638,
    "radarHeight": 1638,
    "projection": {
      "xScale": 0.00023925592675892612,
      "xOffset": 0.5521594968511373,
      "yScale": -0.0002392319458346317,
      "yOffset": 0.49713083123272883,
      "altitudeSplit": -50,
      "lower": {
        "xScale": 0.00023938276080903866,
        "xOffset": 0.5521396064886831,
        "yScale": -0.00023933439919077623,
        "yOffset": 0.4970068359069916
      }
    }
  },
  {
    "mapName": "de_vertigo",
    "radarUrl": "/maps/vertigo.webp",
    "radarWidth": 1135,
    "radarHeight": 1219,
    "projection": {
      "xScale": 0.0003521545668651981,
      "xOffset": 0.9660837268543839,
      "yScale": -0.0003281382508533713,
      "yOffset": 0.4156657931553236,
      "altitudeSplit": 11700,
      "lower": {
        "xScale": 0.0003521826003254699,
        "xOffset": 0.9661198689466229,
        "yScale": -0.00032813507697790616,
        "yOffset": 0.4156420458933476
      }
    }
  },
  {
    "mapName": "cs_office",
    "radarUrl": "/maps/office.webp",
    "radarWidth": 2048,
    "radarHeight": 1823,
    "projection": {
      "xScale": 0.00023819190246088405,
      "xOffset": 0.4377815323344146,
      "yScale": -0.00026773698528956275,
      "yOffset": 0.3739673221358042
    }
  },
  {
    "mapName": "cs_italy",
    "radarUrl": "/maps/italy.webp",
    "radarWidth": 1830,
    "radarHeight": 1830,
    "projection": {
      "xScale": 0.0001901989714239725,
      "xOffset": 0.5555837000977681,
      "yScale": -0.00019008490911940764,
      "yOffset": 0.5450629225827242
    }
  },
  {
    "mapName": "ar_baggage",
    "radarUrl": "/maps/ar_baggage.png",
    "radarLowerUrl": "/maps/ar_baggage-lower.png",
    "radarWidth": 1024,
    "radarHeight": 1024,
    "projection": {
      "xScale": 0.00038461546035504504,
      "xOffset": 0.5061539458272395,
      "yScale": -0.0003846154603550451,
      "yOffset": 0.4953847129372982,
      "altitudeSplit": -5,
      "lower": {
        "xScale": 0.0003846154603550445,
        "xOffset": 0.5061539458272386,
        "yScale": -0.0003846154603550445,
        "yOffset": 0.49538471293729736
      }
    }
  },
  {
    "mapName": "ar_shoots",
    "radarUrl": "/maps/ar_shoots.png",
    "radarWidth": 1024,
    "radarHeight": 1024,
    "projection": {
      "xScale": 0.00036337209302325646,
      "xOffset": 0.497093023255815,
      "yScale": -0.0003633720930232564,
      "yOffset": 0.7093023255813965
    }
  },
  {
    "mapName": "ar_shoots_night",
    "radarUrl": "/maps/ar_shoots_night.png",
    "radarWidth": 1024,
    "radarHeight": 1024,
    "projection": {
      "xScale": 0.0003633720930232567,
      "xOffset": 0.49709302325581545,
      "yScale": -0.00036337209302325646,
      "yOffset": 0.7093023255813966
    }
  },
  {
    "mapName": "de_ancient_night",
    "radarUrl": "/maps/de_ancient_night.png",
    "radarWidth": 1024,
    "radarHeight": 1024,
    "projection": {
      "xScale": 0.00019531250000000023,
      "xOffset": 0.5767578125000007,
      "yScale": -0.00019531250000000034,
      "yOffset": 0.42265625000000073
    }
  },
  {
    "mapName": "cs_shelter",
    "radarUrl": "/maps/cs_shelter.png",
    "radarWidth": 2048,
    "radarHeight": 2048,
    "projection": {
      "xScale": 0.0002948912312115495,
      "xOffset": 1.016848956016725,
      "yScale": -0.00029487260312229327,
      "yOffset": 1.1219563384809463
    }
  },
  {
    "mapName": "de_boulder",
    "radarUrl": "/maps/de_boulder.png",
    "radarWidth": 2048,
    "radarHeight": 2048,
    "projection": {
      "xScale": 0.0003427672209153914,
      "xOffset": 1.1219127827629554,
      "yScale": -0.0003427333194557811,
      "yOffset": 1.004204244801088,
      "altitudeSplit": 62.757324,
      "lower": {
        "xScale": 0.00034274997989235307,
        "xOffset": 1.1218814968428568,
        "yScale": -0.00034276036168006123,
        "yOffset": 1.004244944828151
      }
    }
  },
  {
    "mapName": "de_debris",
    "radarUrl": "/maps/de_debris.png",
    "radarWidth": 2048,
    "radarHeight": 2048,
    "projection": {
      "xScale": 0.0005022120987854478,
      "xOffset": 1.514162323014441,
      "yScale": -0.0005022059416805925,
      "yOffset": 1.465941017249011
    }
  },
  {
    "mapName": "de_eldorado",
    "radarUrl": "/maps/de_eldorado.png",
    "radarWidth": 2048,
    "radarHeight": 2048,
    "projection": {
      "xScale": 0.0004728280665181425,
      "xOffset": 1.6777049247378404,
      "yScale": -0.00047264083829853224,
      "yOffset": 1.2152913904793623
    }
  },
  {
    "mapName": "de_fachwerk",
    "radarUrl": "/maps/de_fachwerk.png",
    "radarWidth": 2048,
    "radarHeight": 2048,
    "projection": {
      "xScale": 0.00038241463861889423,
      "xOffset": 0.8836550738282095,
      "yScale": -0.0003824137803612376,
      "yOffset": 1.0991541930019493
    }
  },
  {
    "mapName": "de_poseidon",
    "radarUrl": "/maps/de_poseidon.png",
    "radarWidth": 1024,
    "radarHeight": 1024,
    "projection": {
      "xScale": 0.0003241713512210472,
      "xOffset": 0.33921105414100206,
      "yScale": -0.0003241713512210472,
      "yOffset": 0.37811158387039245
    }
  },
  {
    "mapName": "rush_001",
    "radarUrl": "/maps/rush_001.png",
    "radarWidth": 1024,
    "radarHeight": 1024,
    "projection": {
      "xScale": 0.0003930817610062902,
      "xOffset": -0.68553459119497,
      "yScale": -0.00039308176100629036,
      "yOffset": 3.0801886792452913
    }
  }
] as const;
